### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by mattcony** [OttoWinter/esphomedocs#16] opened 2018-07-15 00:29 UTC
Using Hass.io easyhomeyaml add-on. Any ideas for this error, trying to upload to an nodemcu-esp32s board with the basic .yaml file to my device.

Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++)
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_memory_used: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znwj: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_newchunk: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: obstack_free: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdlPvj: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znaj: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_begin: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdaPvj: symbol not found

**Comment by OttoWinter** [comment] 2018-09-28 17:55
Duplicate of https://github.com/OttoWinter/esphomeyaml/issues/19 - sorry, I don't have a fix for this.

**Closed as completed by OttoWinter** 2018-09-28 17:55 UTC
